server:
  port: 3344

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
#          uri: git@github.com:TheFrogtheFlower1996/cloud-config.git #github上面的git仓库名字
          uri: https://github.com/TheFrogtheFlower1996/cloud-config #github上面的git仓库名字
          search-paths:
            - cloud-config
      label: master #读取分支
# http://localhost:3344/master/config-dev.yml 访问地址

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka #注册进 注册中心

