server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver  #mysql驱动
    url: jdbc:mysql://localhost:3306/cloud2022?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


management: #监控端点打开
  endpoints:
    web:
      exposure:
        include: "*"


