server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: false

ribbon: #设置feign客户端超时时间（OpenFeign默认支持ribbon）
  ReadTimeout: 5000 #指的是建立连接所用时间
  ConnectTimeout: 5000 #指的是建立连接后从服务器读取可用资源的时间

feign:
  hystrix:
    enabled: true #开启hystrix 豪猪




